### ISSUE TITLE
Link to site

### ISSUE THREAD

**Issue by jacob-ogre** [jess28/jess28.github.io#1]
You can make a link to your site in the README with brackets and parentheses, e.g., `[my personal website](jess28.github.io)`.

**Comment by jess28** [comment]
I tried that but it didn't work! It added on the link to the repo to the
front of it for some reason

**Comment by jacob-ogre** [comment]
Hmmm...`[my personal website](http://jess28.github.io)` -> [my personal website](http://jess28.github.io)

**Comment by jess28** [comment]
Ah, I had forgotten to put the `http://` in front. Thank you!

**Comment by jacob-ogre** [comment]
I had too! 👍
